### ISSUE TITLE
Update LayerList Widget to v2.5

### ISSUE THREAD

**Issue by torrin47** [USEPA/EnviroAtlas_JSApp#73] opened 2017-08-14 23:38 UTC
We significantly customized this, so it's going to take some care to merge.  COTS v2.5 code attached.
[LayerList.zip](https://github.com/USEPA/EnviroAtlas_JSApp/files/1223738/LayerList.zip)

**Comment by Baohong** [comment] 2017-08-23 15:08
LayerList upgrade has been committed.
A demo of the original LayerList version 2.5 could be found in link https://leb.epa.gov/Projects/EnviroAtlas/CurrentDevelopment/EnviroAtlas_Layerlist25/
We can see that there is a button on upper-right corner of Layerlist widget with four functions (Turn all layers on, Turn all layers off, Expand all layers, Collapse all layers). But in my upgraded version (https://leb.epa.gov/EnviroAtlas_2/). such button cannot be found. Because I have spent past 2 days upgrading my laptop to windows 10, I need some more time to add this button.

**Comment by Baohong** [comment] 2017-08-31 17:48
https://leb.epa.gov/EnviroAtlas_2/ is updated with the button on upper-right corner added.
I did not adjust the style of "RemoveAll" button, wondering whether we should incorporate it into the upper-right corner button.
One other problem is the displaying of the right-hand button for each layer. It is not showing, but user can click it. The cause of the problem is that the image is not available:
https://leb.epa.gov/EnviroAtlas_2/widgets/LayerList/images/more_hover.svg
While other type of images (such as png, gif)  can be displayed. I suggest to replace the .svg image with some other image types. We can discuss it in the meeting.

**Comment by torrin47** [comment] 2017-08-31 17:55
It’s likely that .svg just needs to be added as a recognized MIME type in IE. No big deal.

**Comment by brosenbaum** [comment] 2017-09-15 17:44
Torrin added the .svg file type to MIME type to leb IIS during our code call. Need to add to production servers, also.

**Comment by torrin47** [comment] 2017-09-20 16:50
Tile cache/feature service combined national layers should not have the greyed out scale visibility function enabled, but all other layers should grey out when out of scale.
Otherwise, this looks great, let's call it good and move to the next widget!

**Closed** 2017-10-25 17:18 UTC
